version: "3"
services:
  api:
    # replace username/repo:tag with your name and image details
    image: raimojohanson/vet-api:initial
    container_name: vet-api
    ports:
      - "3010:3010"
    networks:
      - vetnet
  postgres:
    image: postgres:10-alpine
    container_name: vet-postgres
    volumes:
      - $HOME/volumes/vet/postgres:/var/lib/postgresql/data
    networks:
      - vetnet
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=vetbase
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=super1user2password
networks:
  vetnet:
    driver: bridge